# Generated by Django 5.2.8 on 2025-11-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(max_length=512)),
                ('risk_score', models.FloatField()),
                ('matched_tag', models.CharField(blank=True, max_length=64, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
